name : my hello world job

on :
    push:
     branches: ["main"]
    pull:
     branches: ["main"]

jobs:
  hello-job:
   runs_on: ubuntu-latest

   steps:
   -name: Echo text
    run: echo "Hello, world!"
